AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Naute — markdown note-taking app

Parameters:
  DomainName:
    Type: String
    Description: Custom domain for the frontend

  HostedZoneId:
    Type: String
    Description: Route 53 hosted zone ID

  CognitoDomainPrefix:
    Type: String
    Description: Globally unique prefix for the Cognito hosted UI domain

Globals:
  Function:
    Runtime: nodejs22.x
    Architectures:
      - arm64
    MemorySize: 256
    Timeout: 30
    Environment:
      Variables:
        TABLE_NAME: !Ref NauteTable
        ALLOWED_ORIGIN: !Sub "https://${DomainName}"

Resources:
  # ──────────────────────────────────────────────
  # Database
  # ──────────────────────────────────────────────
  NauteTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: naute-table
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - { AttributeName: PK, AttributeType: S }
        - { AttributeName: SK, AttributeType: S }
      KeySchema:
        - { AttributeName: PK, KeyType: HASH }
        - { AttributeName: SK, KeyType: RANGE }

  # ──────────────────────────────────────────────
  # Auth (Cognito)
  # ──────────────────────────────────────────────
  UserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      UserPoolName: naute-user-pool
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 12
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      MfaConfiguration: OPTIONAL
      EnabledMfas:
        - SOFTWARE_TOKEN_MFA
      UserPoolAddOns:
        AdvancedSecurityMode: "OFF"

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref CognitoDomainPrefix
      UserPoolId: !Ref UserPool

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: naute-web-client
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
        - email
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - !Sub "https://${DomainName}/callback"
        - http://localhost:5173/callback
      LogoutURLs:
        - !Sub "https://${DomainName}"
        - http://localhost:5173
      AccessTokenValidity: 1
      IdTokenValidity: 1
      RefreshTokenValidity: 30
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      PreventUserExistenceErrors: ENABLED

  # ──────────────────────────────────────────────
  # API Gateway + Lambda
  # ──────────────────────────────────────────────
  NauteApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: naute-api
      StageName: v1
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
      Domain:
        DomainName: !Sub "api.${DomainName}"
        CertificateArn: !Ref ApiCertificate
        Route53:
          HostedZoneId: !Ref HostedZoneId

  ApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "api.${DomainName}"
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Sub "api.${DomainName}"
          HostedZoneId: !Ref HostedZoneId

  NotesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      CodeUri: ../backend/src/handler.ts
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NauteTable
      Events:
        ListNotes:
          Type: Api
          Properties:
            RestApiId: !Ref NauteApi
            Path: /notes
            Method: GET
        CreateNote:
          Type: Api
          Properties:
            RestApiId: !Ref NauteApi
            Path: /notes
            Method: POST
        GetNote:
          Type: Api
          Properties:
            RestApiId: !Ref NauteApi
            Path: /notes/{id}
            Method: GET
        UpdateNote:
          Type: Api
          Properties:
            RestApiId: !Ref NauteApi
            Path: /notes/{id}
            Method: PUT
        DeleteNote:
          Type: Api
          Properties:
            RestApiId: !Ref NauteApi
            Path: /notes/{id}
            Method: DELETE
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: es2022
        Sourcemap: false
        EntryPoints:
          - handler.ts
        Banner:
          - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);
        External:
          - "@aws-sdk/client-dynamodb"
          - "@aws-sdk/lib-dynamodb"

  # ──────────────────────────────────────────────
  # Frontend Hosting (S3 + CloudFront + Route53)
  # ──────────────────────────────────────────────
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: naute.app
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"
            Condition:
              StringEquals:
                "AWS:SourceArn": !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${FrontendDistribution}"

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  FrontendCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId

  FrontendDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: naute.app
        Enabled: true
        DefaultRootObject: index.html
        Aliases:
          - !Ref DomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref FrontendCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        PriceClass: PriceClass_100
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontOAC
            S3OriginConfig:
              OriginAccessIdentity: ""
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html

  FrontendDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt FrontendDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  ApiUrl:
    Description: API endpoint URL
    Value: !Sub "https://api.${DomainName}/v1"

  FrontendUrl:
    Description: Frontend URL
    Value: !Sub "https://${DomainName}"

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient

  CognitoDomain:
    Description: Cognito domain prefix
    Value: !Ref CognitoDomainPrefix

  FrontendBucketName:
    Description: S3 bucket for frontend assets
    Value: !Ref FrontendBucket

  CloudFrontDistributionId:
    Description: CloudFront distribution ID
    Value: !Ref FrontendDistribution

  TableName:
    Description: DynamoDB table name
    Value: !Ref NauteTable
